version: '3.8'

services:
  api:
    build: .
    container_name: api_container
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/roadmap
    networks:
      - app-network
    volumes:
      - .:/app

  mongodb:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
  